{% set name = "concurrent-ruby" %}
{% set version = "1.3.3" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 4f9cd28965c4dcf83ffd3ea7304f9323277be8525819cb18a3b61edcb56a7c6a

build:
  noarch: generic
  number: 0
  script:
    - gem install --norc -l -V --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem

requirements:
  host:
    - ruby >=2.7,<3
  run:
    - ruby >=2.7,<3

test:
  commands:
    - ruby -r concurrent -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: {{ name }}-{{ version }}/LICENSE.txt
  summary: Modern concurrency tools including agents, futures, promises, thread pools, actors, supervisors, and more.

  doc_url: http://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/ruby-concurrency/{{ name }}

extra:
  recipe-maintainers:
    - sodre
    - svengiegerich
    - janjagusch
