{% set name = "concurrent-ruby" %}
{% set version = "1.1.8" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: e35169e8e01c33cddc9d322e4e793a9bc8c3c00c967d206d17457e0d301f2257

build:
  noarch: generic
  number: 0
  script:
    - gem install --norc -l -V --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby

test:
  commands:
    - ruby -r concurrent -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: {{ name }}-{{ version }}/LICENSE.md
  summary: Modern concurrency tools including agents, futures, promises, thread pools, actors, supervisors, and more.

  doc_url: http://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/ruby-concurrency/{{ name }}

extra:
  recipe-maintainers:
    - sodre
