{% set name = "concurrent-ruby" %}
{% set version = "1.3.6" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 6b56837e1e7e5292f9864f34b69c5a2cbc75c0cf5338f1ce9903d10fa762d5ab

build:
  noarch: generic
  number: 0
  script:
    - gem install --norc -l -V --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem

requirements:
  host:
    - ruby
  run:
    - {{ pin_compatible('ruby', max_pin='x.x') }}

test:
  commands:
    - ruby -r concurrent -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: {{ name }}-{{ version }}/LICENSE.txt
  summary: Modern concurrency tools including agents, futures, promises, thread pools, actors, supervisors, and more.

  doc_url: http://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/ruby-concurrency/{{ name }}

extra:
  recipe-maintainers:
    - sodre
    - svengiegerich
    - janjagusch
    - abloemert
