schema_version: 1

context:
  name: concurrent-ruby
  version: 1.3.5

package:
  name: rb-${{ name|lower }}
  version: ${{ version }}

source:
  url: https://rubygems.org/downloads/${{ name }}-${{ version }}.gem
  sha256: 813b3e37aca6df2a21a3b9f1d497f8cbab24a2b94cab325bffe65ee0f6cbebc6

build:
  number: 1
  noarch: generic
  script:
    - gem install --norc -l -V --ignore-dependencies ${{ name }}-${{ version }}.gem
    - gem unpack ${{ name }}-${{ version }}.gem

requirements:
  host:
    - ruby
  run:
    - ${{ pin_compatible('ruby', upper_bound='x.x') }}

tests:
  - script:
      - "ruby -r concurrent -e 'exit 0'"

about:
  license: MIT
  license_file: ${{ name }}-${{ version }}/LICENSE.txt
  summary: Modern concurrency tools including agents, futures, promises, thread pools, actors, supervisors, and more.
  homepage: https://rubygems.org/gems/${{ name }}
  repository: https://github.com/ruby-concurrency/${{ name }}
  documentation: http://www.rubydoc.info/gems/${{ name }}

extra:
  recipe-maintainers:
    - sodre
    - svengiegerich
    - janjagusch
    - abloemert
